apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:TfZMiPYPagCR+UMdqsfhteKI3LTG6mjGe4R7dVfIduIpk9CWy+ggqQ==,iv:ct4unwl8wrYpgUR4KxDi71vZmnOqE1tZRdXwFZrmHyk=,tag:8PMzkWnAtijfcb3WKnWH0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1axjvaaje8z3lxau7ekm30pjrrdjkxnjyrxrl84tmz6qfjvdm5ulqjmqecr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaW9LN3MvN1RPUEEySWQz
            TDdRa1dTSWV2Rmd2MG9RQ0U0clRLajRSaVdRClZxRDFHMHpyOGE5MS9Wcm94anhK
            ZHJFOFVsdlF4Y1pUOHh4VEhqZVd6SGsKLS0tIG9LdVQ1ZHlMSU1XWmdRalRpbnl1
            R2pqMEhLaytlRVo4bzVNdG94b2dzeXcKOR0aRNsUxepChGMaCKH2IwVU76JIsNQV
            H/xJrlSAUy3wo+2or1BO8al/zKyPSSrrQP+z0aejyMAp4wGlH2IAjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-14T10:23:58Z"
    mac: ENC[AES256_GCM,data:PGzthxea895mz8dWz9FEnh6UIAWLJvlxfwweJjOqX9Fnsn2OZ2+I1sfuJFZUHGoY6TE+MUxxJqu8zzAUsbRiFcExcEL/nnJPaYIncU690Gw6zbpIbqArHkT7srUdJPlLlvTxJhgw2oqlWof/3Wt8U6cX8S9OppJfawlJqWbmeaw=,iv:biCvY1YmOpdztNn1hWalDGHSmWMmQmZ+vlreEenOtMo=,tag:GLF1JgpApDBFt0a6IUTtWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
