apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:mFXZDi+lhDH2A7RRYwaLbzHrpaifaM/YGHFx3vy3Kp+nZY70N7+hbw==,iv:s5vKqBHM4JiIheHfxAcpkUaghOjSNeL0uBQYKV8s458=,tag:FzLo4sFY7hkw5xsluFAklQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1axjvaaje8z3lxau7ekm30pjrrdjkxnjyrxrl84tmz6qfjvdm5ulqjmqecr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPaldoc0pTVjc0RVRJalVW
            U2cxSDNMNGRmNFIwN01vdnFSUlJJa3pQa2tnCmNxbjhJVytOcFlIOTJGZ3p4NEdX
            ckJzeVQ0bjZvZFFwSThsQUx3Umg4KzAKLS0tIElORExlbWRydVJpNGhnOGJiWFRX
            dXd5Q3FERG5LRkdtWllqdlVLSHhzRVkKMtTMlfYR7n9GTI06X77uCrr+sTw3cyEr
            vLisQLT8m7ziw/jIphTDyKIwTYsxbf1uEhVGWNOMKH9wZykebtElIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-19T00:11:18Z"
    mac: ENC[AES256_GCM,data:1jikxti3wugSUgTVEi41Iqn4SssOuYawnggaz9pVmHc6ypg10qVr+airCFmzAksOeQ+oa2+ELz4ujKQwqiycZg/IKdNuqcSA3KS627KjYtAd/wG3S33WEPRhKUBysxED8fy3d/1F2EWT7Kgoe1iBrTGuCYN90YWDYpljd432Wcw=,iv:YSPreY68lnUZ237OjHPqrF7kGa1Ty/tWvMVqCtV9eTo=,tag:ZvMN8qDpa0Nu4BPYCdr2DQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
