apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:husLa1CV42f4SU7TB//7DOJ+fwLDazrv8aUcdSttYnsuG7j/i20xeA==,iv:KG6LYY7NfWemXq0/hhtppF/4BhSjtX6zDJf+l2994Qo=,tag:jGKB0x8SQTJE6bvlF/YcJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1axjvaaje8z3lxau7ekm30pjrrdjkxnjyrxrl84tmz6qfjvdm5ulqjmqecr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWktZOVBzOFNUZW9Ec0Ry
            Z3Q3Y0MzN1hwMGl3ZjUrcWRBdFlHTjA4ZnhvCmhTNlNuenBxZ05jS1F1UzhHN2FE
            L3dubjF1K2VhQ0NjUGJobTdUTllaRXMKLS0tIFhteG1LcDJaSzlGbU5xNDJpWnZs
            Q1FjeTd1ZzhNM1BkV3VsaVlydGRoSUkKf6gU4KccdwX74+DRWmWX3EIiDY2GVyVy
            ZtZ9/BjVZBjp8CTYTsb+Q1kEE3+iNlsJPlLTSOhDtETIzChc/ThxAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-14T10:23:58Z"
    mac: ENC[AES256_GCM,data:4OS7OWpz7o0vyvj6u9UjeG6q/0fooXYgfBI/oGGyAN1M5VbDQ+kA/2RauwZyf9+uaEkR5AFN0c/zvnjjV7QRUYlEEcfDTW7bifzWGeYFNdED22Fa1j17400BNYxttJsnGfjCe2plPbC+njuQ5xqk/+YSKYojOTOJ7ztwYpRExso=,iv:zvfVCcUrLB+2TlmpGin3PIuMgOjLK37y1+JUe7GGcD0=,tag:zUda8EOt/KnBRkU7FVc3xA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
