apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:Y+ZqZxXwbl+0egUGMdrae65T75Vx2cgvPskfcaydXvIuDVpgvcC4Zw==,iv:loUtIW9h+YfCURSAV5cIXOAM/yhX9ASicDP4O8arQMQ=,tag:q/v69M/jNsLmJupf/+o+9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1axjvaaje8z3lxau7ekm30pjrrdjkxnjyrxrl84tmz6qfjvdm5ulqjmqecr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3U1hwYmtDL1E3YlcxYWpv
            bUdzU2I5aXNpNitiVGJ3RUN1dnNVVkFQbVVzClhsM3g4RUx6d1dIVEkySDFWa3Zk
            RTV0N0V4QlBxN0U0V20yNDdSQ2JPK2cKLS0tIGdqNzlzaXR5TnE1aXJXbVlQazJE
            OGFEeEdWbkdCNUhOL2lta2tHaFRWZGcKkbojJ0PRvDajQKC6zk7MGLLfmgSSzL+T
            XZRwl1YV29UePRov0dXZfV3oqTTgwcqzKe6yTGVVqd2oMsIXKr0erw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-14T10:23:58Z"
    mac: ENC[AES256_GCM,data:TXdt71OMR+I02JojszdmJ9HPM8PWnTcyZVv13MmS8Nq2po3C8ZCZeQSipbavvSZ8kIokZMpx7rWx+TkHGmfQ755/56YhxgbYjzJZoZlfRlg2heuXi21NGLnq5PIVi7Tq4MvTH15Lth2IpQRHUG5MKY08xXgCzf7FsfUMYj4zfBQ=,iv:ACQXe+O6tGRR+hu9o5iuWvof62tP/dEs8nNEj+XU5mA=,tag:nmhKKee0ZcAIKzq7zB/7FA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
