apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:44xOif79sznrvhdLtQ1MYtbkakMb4JlO,iv:RtB3CuN4+CJHn8CtL+TwpvoDV/skZ+d9jDbUpSUtNJE=,tag:zT7XXst+KSWHG+iuPoXdjQ==,type:str]
    username: ENC[AES256_GCM,data:M2MCFUM=,iv:P6udB8lygfAHl/DVNoj2LJVV52Sm2JXFPHJIMGn4aPc=,tag:6KgN2wNRbz21Zj3gs4JUSQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1axjvaaje8z3lxau7ekm30pjrrdjkxnjyrxrl84tmz6qfjvdm5ulqjmqecr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Q2hob3Z5SWlaZlY2QmdB
            dkJpMncvUDNoNHp4YVNlK0tTWlcrdTZMN25FCm5tN1Viak15cDEzK05MdFZUYlhX
            RUxoYkhvRlEvQlREWG90dDVBOC9DZlUKLS0tIENtNTB1eE1XSjhSTFBIb0NjcXhF
            cUx6dWJydW5jZkZENk1HM0ZYcllMMk0KRmtwrs1qUsjhaL0dPWsxMcN7zbUPpKuX
            cb3LTa13TgafS391TPJYOf9FhAbdZXH9YF/xYkmtKNmnPPGi1Xp4Gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-14T11:53:28Z"
    mac: ENC[AES256_GCM,data:Qo8Ue6e12l9wnOP4RionThh1CvqwgUjNk7m7qFpOzi8MPuJ2/nObcsYX6uif4nulFb+ntHdfgV1o/68nNhDtOdkymsNOL2TJZEaSt6cKHSYQVHPRROIZ1nV/z8h0+8a6uPp5TqeYQV9QR7yfv9lbVa7AYYADnhpBzZrYF1ihbAc=,iv:xrbyY9SLyELOa1Zauf+6JJIlwHdWk/GQ58ldhOqTccM=,tag:hx903oYUCJzA/kmXRjuepw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
