apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:E3JHRolfPlXxYWqN,iv:7fmEp16hyMbuWqopf4xn6U/27JchWF912nXafV/v0dc=,tag:NUR5ixsKEdqcDogknVsgog==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:zM5s14+m8kwVzH1bm1y3Cdw7dE/GKNE=,iv:nVgxGruCs9MEgppaGecngtdKHn0W3XUkbiIICkCG5SM=,tag:/a6Oh9Youx9tkurXAwVIKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1axjvaaje8z3lxau7ekm30pjrrdjkxnjyrxrl84tmz6qfjvdm5ulqjmqecr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZ3ZpWURzUC9NdkxPRWlR
            QXQ3M2pVaEVYbkZIay90Tnd0bXVqK3pQcW5nCmcxTjVJZThYWU03QXJ6WFovZ0d3
            c3FFM1hnVVpUOVZKQ3NLVU96RDkwaUkKLS0tIDBLYVJWY3o0YzBuUmZtdTFSSHNT
            ZkgyZVlMSjIybGpJREtHakpPSVdOY3MKH2wpkdHvuAGaD1roT+Q2y1JaosN+dhNk
            bEArKXSqE7M7c8iAztX545UVYUyZzObZs0TWzY0AGvy5GMIL5xbULA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-19T00:11:18Z"
    mac: ENC[AES256_GCM,data:i5NLMv20XeX9rOl4RQ22FcMiXGl2k9yzmFSqE3ZK3cY+6h8A1qakdO9Np6fYuJFbMMErWrHLjEy45geYKgV2tSOUot0RkWDrg75RuEMjaCaZOLOWO1/632HAdPq7C8wB7zC3G6185xIJYwEqeDtCeyifEHu9MBibVgcoLKtAMhg=,iv:FEP6g3PRCbYso1ZgnvCO/xgPAo3h78314C+ru2/GJzI=,tag:oip+dMwVvzTQV0UyPX1ryg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
