---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Paris"
  KUBE_VIP_ADDR: "192.168.50.254"
  METALLB_LB_RANGE: "192.168.50.247-192.168.50.253"
  METALLB_K8S_GATEWAY_ADDR: "192.168.50.247"
  METALLB_INGRESS_ADDR: "192.168.50.248"
