apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:RhuHn7G8oM5DISP5JO1FgpAtoWSwoAc=,iv:YFY8luzWOQM9rZ975r679aysicPX+Qfff3CfjYGyFuo=,tag:+u4rICHxhciq/j0/tnjqIg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:lq7RNN0ljwki1BjD6LoSYInEwJ2/eC6YtFHrs5Pnsz65k4BW,iv:pfXydKVXsXdKP6ScKYazGzdms5hh2fAzQFtHsd6mNEA=,tag:9EGdy+1FGSQX6Gj7NBgKRg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:+uvcTCV5esChRt/l,iv:PLP9ctiJVNVL63cWE+DYMFEO0NAKwJH4XOQrF1KOXUs=,tag:MBqTdJH+k9VuI70eR6NI6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1axjvaaje8z3lxau7ekm30pjrrdjkxnjyrxrl84tmz6qfjvdm5ulqjmqecr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Uy85RXFJdHZPcm9QWDdH
            azNXWjZWM3Q4T09wdWt3NjJYRzkvdWRnM0NJCkdjNjFBc09sdkFuMmNLL2dwdnMw
            OCtpSjd1cEV5R0VQdno1T2Q1dmJmQ3cKLS0tIFRxZWM5SjdRYmtONkU4ZFBSTml6
            SmFEUkkwN0dhNy9kVDIveXRPQVRBVk0KOJFRWN0dGDKd+zz88XMfRj/hDD98bgKt
            638yMinayolvcvs4kbkdx4Np7BuLIIT+qzui+/k8viG74Qt9yqCsYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-14T10:23:58Z"
    mac: ENC[AES256_GCM,data:I8r6bL2FkZwpcAsIVu2cxzW3MciExjpDKBvx1PqwOzFpCWj7V6Szc3ULEgn00lo1Bbt3Iq2VfqRSo1RR/54/2gw/dWLQjXq9VaUwtKt2QwI9ecbrGLKKGKKTHmMdLaUwb0FAExKUAc6gDOeaxyToxneoZxIYh4/PrNMziVMIdes=,iv:r/2H4FNK2Lhwwszajb4C/YsvAOGZH/Pw7VaEx+1jnPg=,tag:0qwl2XR9jMXtwvQj0yilfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
