apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:WHwh/rBCb0Y46mIuTapvBQNcl/W3f8m5xESRcqqGKglYYMrj,iv:zAdh1b+SbYeHJh+Y5Ch9EEOp1aSgZTii5wI1XbrdCEg=,tag:HDvaclo6wQHPIcgYESu+9w==,type:str]
    credentials.json: ENC[AES256_GCM,data:VilDq7YRMDM71ztv6E9zWpG+xlxiltCiJDw40WtbRHHwjQGZgc/F0A9OnIJDnxCMzLC9tIKJ10YunOHf6I/E3rQhYOMppWivnKeJjY426kdy1X/edr50PFtF2+AwYhJ2VFUGLyP4j1d10uVvwpmwTGapRtly84YHz7P88XTt93Wh6h120VJcrBBDy6dQVT173zZwrJuuexYg6Ut9Wk9mqekw69dbl6sPdO4yMPGuaA==,iv:AtQE0q+rdwsrvfZOW5I44mO0KM/twoBAmg+pzoEKEFs=,tag:YbvD4yDKuopvaOQsAwCpyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1axjvaaje8z3lxau7ekm30pjrrdjkxnjyrxrl84tmz6qfjvdm5ulqjmqecr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MytseGtENnNrSXlTSVRs
            VG5FQ2ovdnpMeTUvWEFHNXFwRUpGWklBQ1I4ClYwY1J1K3Q3aXBhZDFBaDNYZ3ZB
            Z042dUtIN1hyRlJjbGFJTzUvRE1CQUEKLS0tIHlSaHc0ZnhVRWYxWDhvOTQ4Y1RV
            SjgwV1RGNHVPS2lJOXVrZzNSTEYxV2MKeaX4HyDMfoirO8f1s8qE456BcfsVQOdV
            Fj9TOy3Y/30YZQh8L/7oheS7M5aQIVFDdsHGrMtZcCUB1TQhhLajNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-14T10:23:58Z"
    mac: ENC[AES256_GCM,data:WvAH7KasK48xu6Gh/hbTMwU+Id8Pu3XGMXbZgAXAxs4JAyfu/SxpYA/PnLcvCZdgt6Sf6IiaXC0WiI4LEXEBLgzx2AFnwokgzV85hg4ZpeCoc9E2oA1AuDNbhJr/ljh2oG3HtEZT/XiiltrHrwL1yFlkdgGwsJSYzPN667mDPII=,iv:Pohwqi8+ASPeEFBb77AzdR7640XpUPECnHhqSIIMPds=,tag:e30ovz56mTZO10ag7X2Sow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
